[package]
name = "cardano"
version = "0.0.4"
authors = ["Clemens Horn <clemens.horn@mni.thm.de>"]
edition = "2021"
license = "MIT"
description = "CLI for managing cardano components"

[dependencies]
lib = { path = "../lib" }
clap = { version = "3.2.8", features = ["derive"] }
clap_complete = "3.2.3"
human-panic = "1.0.3"
ctrlc = "3.2.2"
anyhow = "1.0.58"
tokio = { version = "1.19.2", features = ["full"] }
log = "0.4.17"
clap-verbosity-flag = "1.0.1"

[dev-dependencies]
assert_cmd = "2.0.4"
predicates = "2.1.1"
pretty_assertions = "1.2.1"
